import React from 'react';

const Terms = () => {
  return (
    <div
      style={{
        padding: '40px 20px',
        maxWidth: '800px',
        margin: '0 auto',
        fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        lineHeight: '1.6',
        color: '#333',
      }}
    >

    <button
  onClick={() => window.dispatchEvent(new Event('close-legal'))}
  style={{
    marginBottom: '24px',
    fontWeight: 600,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#333',
    padding: 0
  }}
>
  ← Back
</button>
      <h1 style={{ borderBottom: '1px solid #eee', paddingBottom: '16px', marginBottom: '24px' }}>
        Terms of Service for FitCheck AI
      </h1>

      <p style={{ color: '#666', fontSize: '0.9rem', marginBottom: '32px' }}>
        Last Updated: February 3, 2026
      </p>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>1. Acceptance of Terms</h2>
        <p>
          By creating an account, accessing, or using FitCheck AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not access or use the Service.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>2. Description of Service</h2>
        <p>
          FitCheck AI provides AI-powered fashion analysis, style scores, and outfit recommendations based on user-uploaded images. The Service uses third-party Artificial Intelligence (Google Gemini) to process data.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>3. User Conduct & Acceptable Use</h2>
        <p>You are solely responsible for the content you upload. You agree NOT to upload:</p>
        <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
          <li>Content that is illegal, pornographic, hateful, or promotes violence.</li>
          <li>Images that infringe on the intellectual property or privacy rights of others.</li>
          <li>Malicious code, viruses, or data intended to disrupt the Service.</li>
        </ul>
        <p style={{ marginTop: '12px', fontWeight: '500', color: '#d32f2f' }}>
          <strong>Zero Tolerance Policy:</strong> We have zero tolerance for objectionable content or abusive users. Any user found uploading such content will have their account immediately terminated and content removed.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>4. AI Disclaimer</h2>
        <p>
          You acknowledge that the style feedback and scores are generated by Artificial Intelligence. 
          <strong>The Service makes no guarantees regarding the accuracy, cultural sensitivity, or objective "correctness" of the fashion advice provided.</strong> 
          Outputs should be treated as entertainment and suggestions, not professional advice.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>5. Account Security</h2>
        <p>
          Access to features requires authentication via Google. You are responsible for safeguarding your account credentials. We are not liable for any loss or damage arising from your failure to protect your account.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>6. Intellectual Property</h2>
        <p>
          You retain ownership of the images you upload. However, by uploading, you grant FitCheck AI a license to process the image solely for the purpose of providing the analysis. 
          The application interface, branding, and underlying code are the exclusive property of FitCheck AI.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>7. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, FitCheck AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.
        </p>
      </section>

      <section style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>9. Changes to Terms</h2>
        <p>
          We may modify these Terms at any time. If we make material changes, we will provide notice through the Service. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.
        </p>
      </section>

      <section style={{ marginTop: '40px', borderTop: '1px solid #eee', paddingTop: '20px' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '12px' }}>10. Contact Information</h2>
        <p>
          For any questions about these Terms, please contact us at:
          <br />
          <a href="mailto:abimbolaabdsamad07@gmail.com" style={{ color: '#0066cc', textDecoration: 'none' }}>
            abimbolaabdsamad07@gmail.com
          </a>
        </p>
      </section>
    </div>
  );
};

export default Terms;